services:
  ngrok:
        image: ngrok/ngrok:latest
        restart: unless-stopped
        command:
          - "start"
          - "--all"
          - "--config"
          - "/etc/ngrok.yml"
        volumes:
          - ./ngrok.yml:/etc/ngrok.yml
        ports:
          - 4040:4040
  #dbコンテナ
  db:
    image: mariadb:10.9
    environment:
      MARIADB_ROOT_PASSWORD: password
    volumes:
     - db-data:/var/lib/mysql
  #webコンテナ
  web:
    build: .
    depends_on:
      - db
    environment:
      DATABASE_PASSWORD: password
    ports:
      - "3000:3000"
    volumes:
      - .:/mofucode_back
volumes:
  db-data:

  